# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["csoc@fastly.com"]
description = "meep"
language = "rust"
manifest_version = 3
name = "mss compute poc for rust"
service_id = "UDjLLnd2cGb98HcrEcfjj0"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
